# Numpy

In [1]:
# Importing the numpy library for numerical operations
import numpy as np

## Why is NumPy faster than Lists

<ol>
    <li>Fixed-Size, Homogeneous Data Types</li>
    <li>Contiguous Memory Allocation</li>
    <li>Vectorization and Broadcasting</li>
    <li>Optimized C Backend</li>
    <li>Memory Efficiency</li>
    <li>Lower-Level Operations</li>
    <li>No type checking when iterating through objects</li>
</ol>

## Applications of NumPy : 

<ol>
    <li>Scientific Computing</li>
    <li>Data Science and Data Analysis</li>
    <li>Machine Learning and Deep Learning</li>
    <li>Image and Signal Processing</li>
    <li>Backend (pandas, Connect 4, Digital Photography</li>
    <li>Finance and Economics</li>
</ol>

### The Basics

In [2]:
# Create a NumPy array
arr1 = np.array([1, 2, 3])

# Print the array
print(arr1)

[1 2 3]


In [3]:
# Create an int16 array
arr2 = np.array([1, 2, 3], dtype="int16")

# Print the int16 array
print(arr2)

[1 2 3]


In [4]:
# Create a 2D NumPy array
arr3 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]])

# Print the 2D array
print(arr3)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [5]:
# Create a 3D NumPy array
arr4 = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]], [[9, 8, 7, 6, 5], [4, 3, 2, 1, 0]]])

# Print the 3D array
print(arr4)

[[[1 2 3 4 5]
  [6 7 8 9 0]]

 [[9 8 7 6 5]
  [4 3 2 1 0]]]


In [6]:
# .ndim returns the number of dimensions (axes) of the array

# Get the number of dimensions of arr1
dims_arr1 = arr1.ndim

# Get the number of dimensions of arr2
dims_arr2 = arr2.ndim

# Get the number of dimensions of arr3
dims_arr3 = arr3.ndim

# Get the number of dimensions of arr4
dims_arr4 = arr4.ndim

# Print the number of dimensions for all arrays
print("Number of dimensions of arr1:", dims_arr1)
print("Number of dimensions of arr2:", dims_arr2)
print("Number of dimensions of arr3:", dims_arr3)
print("Number of dimensions of arr4:", dims_arr4)

Number of dimensions of arr1: 1
Number of dimensions of arr2: 1
Number of dimensions of arr3: 2
Number of dimensions of arr4: 3


In [7]:
# .shape gives the dimensions (shape) of the array, i.e., the number of elements in each axis

# Get the shape of arr1 (1D array)
shape_arr1 = arr1.shape

# Get the shape of arr2 (1D array with int16 data type)
shape_arr2 = arr2.shape

# Get the shape of arr3 (2D array)
shape_arr3 = arr3.shape

# Get the shape of arr4 (3D array)
shape_arr4 = arr4.shape

# Print the shapes of all arrays
print("Shape of arr1:", shape_arr1)
print("Shape of arr2:", shape_arr2)
print("Shape of arr3:", shape_arr3)
print("Shape of arr4:", shape_arr4)

Shape of arr1: (3,)
Shape of arr2: (3,)
Shape of arr3: (2, 5)
Shape of arr4: (2, 2, 5)


In [8]:
# .dtype returns the data type of the array elements

# Get the data type of arr1
dtype_arr1 = arr1.dtype

# Get the data type of arr2
dtype_arr2 = arr2.dtype

# Get the data type of arr3
dtype_arr3 = arr3.dtype

# Print the data types of all arrays
print("Data type of arr1:", dtype_arr1)
print("Data type of arr2:", dtype_arr2)
print("Data type of arr3:", dtype_arr3)

Data type of arr1: int64
Data type of arr2: int16
Data type of arr3: int64


In [9]:
# .itemsize returns the size of a single array element in bytes

# Get the size of a single element in arr1 in bytes
itemsize_arr1 = arr1.itemsize

# Get the size of a single element in arr2 in bytes
itemsize_arr2 = arr2.itemsize

# Print the item sizes
print("Item size of arr1:", itemsize_arr1, "bytes")
print("Item size of arr2:", itemsize_arr2, "bytes")

Item size of arr1: 8 bytes
Item size of arr2: 2 bytes


In [10]:
# .size returns the total number of elements in the array

# Get the total number of elements in arr1
size_arr1 = arr1.size

# Get the total number of elements in arr2
size_arr2 = arr2.size

# Get the total number of elements in arr3
size_arr3 = arr3.size

# Get the total number of elements in arr4
size_arr4 = arr4.size

# Print the total number of elements for all arrays
print("Number of elements in arr1:", size_arr1)
print("Number of elements in arr2:", size_arr2)
print("Number of elements in arr3:", size_arr3)
print("Number of elements in arr4:", size_arr4)

Number of elements in arr1: 3
Number of elements in arr2: 3
Number of elements in arr3: 10
Number of elements in arr4: 20


In [11]:
# .nbytes returns the total number of bytes consumed by the array
# This is equivalent to size * itemsize (total elements * size of each element in bytes)

# Get the total number of bytes consumed by arr1
bytes_arr1 = arr1.nbytes

# Get the total number of bytes consumed by arr2
bytes_arr2 = arr2.nbytes

# Get the total number of bytes consumed by arr3
bytes_arr3 = arr3.nbytes

# Get the total number of bytes consumed by arr4
bytes_arr4 = arr4.nbytes

# Print the total number of bytes for all arrays
print("Total bytes consumed by arr1:", bytes_arr1)
print("Total bytes consumed by arr2:", bytes_arr2)
print("Total bytes consumed by arr3:", bytes_arr3)
print("Total bytes consumed by arr4:", bytes_arr4)

Total bytes consumed by arr1: 24
Total bytes consumed by arr2: 6
Total bytes consumed by arr3: 80
Total bytes consumed by arr4: 160


### Accessing/Changing specific elements, rows, columns, etc

In [12]:
# Create a 2D array with two rows and six columns
arr5 = np.array([[1, 2, 3, 4, 5, 6], [2, 3, 4, 5, 6, 5],[3,4,2,5,7,8]])

# Print the created array
print(arr5)

# Access a specific element
# Syntax: array[row_index, column_index]
element_at_rc = arr5[1, 4]
print("Element at [1, 4]:", element_at_rc)

[[1 2 3 4 5 6]
 [2 3 4 5 6 5]
 [3 4 2 5 7 8]]
Element at [1, 4]: 6


In [13]:
# Access a specific row from the 2D array
# Syntax: array[row_index, :] - Access all columns in the given row

first_row = arr5[0, :]
print("First row:", first_row)

First row: [1 2 3 4 5 6]


In [14]:
# Get a specific part of a row from the 2D array
# Syntax: array[row_index, start_index:end_index:step_size] 
# Access elements from row 0, starting from index 2 onwards

part_of_first_row = arr5[0, 2:]
print("Part of the first row from index 2:", part_of_first_row)

Part of the first row from index 2: [3 4 5 6]


In [15]:
# Access elements from row 0, starting at index 1, and take every 2nd element thereafter
part_of_first_row_step = arr5[0, 1::2]

print(part_of_first_row_step)

[2 4 6]


In [16]:
# Access a specific column from the 2D array
# Syntax: array[:, column_index] - Access all rows in the given column

third_column = arr5[:, 2]
print(third_column)

[3 4 2]


In [17]:
# Get a specific part of a column from the 2D array
# Syntax: array[start_index:end_index:step_size, column_index] - starting from a specific row with optional step size

part_of_first_column = arr5[1:, 0]
print(part_of_first_column)

[2 3]


In [18]:
# Modifying an element in the 2D array
# Access and modify the element at row 1, column 5
arr5[1, 5] = 15

# Print the modified array
print(arr5)

[[ 1  2  3  4  5  6]
 [ 2  3  4  5  6 15]
 [ 3  4  2  5  7  8]]


In [19]:
# Modifying an entire column in the 2D array
# Access and modify all elements in column 6 (index 5) to the value 15
arr5[:, 5] = 15

# Print the modified array
print(arr5)

[[ 1  2  3  4  5 15]
 [ 2  3  4  5  6 15]
 [ 3  4  2  5  7 15]]


In [20]:
# Modifying all elements in the 2D array
# Set all elements in the array to the value 15
arr5[:] = 15

# Print the modified array
print(arr5)

[[15 15 15 15 15 15]
 [15 15 15 15 15 15]
 [15 15 15 15 15 15]]


In [21]:
# Modifying an entire row in the 2D array
# Access and modify all elements in row 1 to the value 16
arr5[1] = 16

# Print the modified array
print(arr5)

[[15 15 15 15 15 15]
 [16 16 16 16 16 16]
 [15 15 15 15 15 15]]


In [22]:
# Modifying a specific column in the 2D array
# Set the elements in column 3 (index 2) to the values [17, 18]
arr5[:, 2] = [17, 18, 19]

# Print the modified array
print(arr5)

[[15 15 17 15 15 15]
 [16 16 18 16 16 16]
 [15 15 19 15 15 15]]


In [23]:
# Create a 3D array with two blocks, each containing two rows and two columns
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Print the created 3D array
print(arr3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
# Access a specific block from the 3D array
# Work outside in: First access the block, then the rows and columns inside it
print(arr3d[1])

[[5 6]
 [7 8]]


In [25]:
# Access a specific row from a specific block in the 3D array
print(arr3d[1, 0])

[5 6]


In [26]:
# Access a specific element from a specific block, row, and column in the 3D array
print(arr3d[0, 0, 0])

1


In [27]:
# Access a specific element from a specific block, row, and column in the 3D array
print(arr3d[1, 1, 0])

7


In [28]:
# Replace the entire second row (index 1) of each block in the 3D array
# Set the second row of all blocks to [10, 11]
arr3d[:, 1, :] = [10, 11]

# Print the modified array
print(arr3d)

[[[ 1  2]
  [10 11]]

 [[ 5  6]
  [10 11]]]


In [29]:
# Access the first column (index 0) of all rows in each block of the 3D array
# This will extract the first column from all rows in both blocks
print(arr3d[:,:, 0])

[[ 1 10]
 [ 5 10]]


In [30]:
# Replace the first column (index 0) of all rows in each block with [0, 0]
arr3d[:,:, 0] = [[0, 0], [0, 0]]

# Print the modified array
print(arr3d)

[[[ 0  2]
  [ 0 11]]

 [[ 0  6]
  [ 0 11]]]


In [31]:
# Replace the second row (index 1) in each block with [10, 11] and [12, 13] respectively
arr3d[:, 1, :] = [[10, 11], [12, 13]]

# Print the modified array
print(arr3d)

[[[ 0  2]
  [10 11]]

 [[ 0  6]
  [12 13]]]


### Initializing different types of Arrays

In [32]:
# Create a 1D array of 0's with 10 elements
zeros_arr = np.zeros(10)

# Print the array of zeros
print(zeros_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [33]:
# Create a 2x3 matrix of 0's with dtype int16
zeros_matrix = np.zeros([2, 3], dtype="int16")

# Print the 2x3 matrix of zeros
print(zeros_matrix)

[[0 0 0]
 [0 0 0]]


In [34]:
# Create a 1D array of 1's with 10 elements
ones_arr = np.ones(10)

# Print the array of ones
print(ones_arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [35]:
# Create a 2x3 matrix of 1's with dtype int16
ones_matrix = np.ones([2, 3], dtype="int16")

# Print the 2x3 matrix of ones
print(ones_matrix)

[[1 1 1]
 [1 1 1]]


In [36]:
# Create a 2x2 matrix filled with the number 99
full_matrix = np.full([2, 2], 99)

# Print the matrix filled with 99
print(full_matrix)

[[99 99]
 [99 99]]


In [37]:
# Create a 3x2 matrix where each row is filled with [1, 2]
full_matrix_rows = np.full([3, 2], [1, 2])

# Print the matrix
print(full_matrix_rows)

[[1 2]
 [1 2]
 [1 2]]


In [38]:
# Create an array with the same shape and type as 'arr4', filled with the number 4
full_like_arr4 = np.full_like(arr4, 4)

# Print the array filled with 4's
print(full_like_arr4)

[[[4 4 4 4 4]
  [4 4 4 4 4]]

 [[4 4 4 4 4]
  [4 4 4 4 4]]]


In [39]:
# Create a 2x3 array with random decimal numbers between 0 and 1
random_decimals_matrix = np.random.rand(2, 3)

# Print the array with random decimal numbers
print(random_decimals_matrix)

# np.random.rand() expects the shape of the array as separate integers

[[0.46875773 0.51397353 0.96864371]
 [0.11158038 0.04399114 0.52498783]]


In [40]:
# Create an array with random decimal numbers between 0 and 1, with the same shape as 'a'
random_sample_arr = np.random.random_sample(arr4.shape)

# Print the array with random decimal numbers
print(random_sample_arr)

[[[0.47685072 0.68202399 0.50757619 0.16081002 0.91168005]
  [0.14241204 0.59890409 0.11259136 0.54451399 0.85319535]]

 [[0.17307307 0.85880481 0.31174735 0.40836648 0.91363704]
  [0.81535291 0.05421918 0.68598056 0.5648272  0.36721116]]]


In [41]:
# Create a 3x3 array with random integers between 0 and 2
random_integers_array = np.random.randint(2, size=[3, 3])

# Print the array of random integers
print(random_integers_array)

[[0 0 0]
 [0 1 1]
 [0 1 0]]


In [42]:
# Create a 3x3 array with random integers between 2 (inclusive) and 8 (exclusive)
rand_ints = np.random.randint(2, 8, [3, 3])

# Print the array of random integers
print(rand_ints)

[[7 2 7]
 [7 7 5]
 [3 6 4]]


In [43]:
# Create a 3x3 identity matrix with dtype int16
identity_matrix = np.identity(3, dtype="int16")

# Print the identity matrix
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [44]:
# Create a 1D array
arr_base = np.array([1, 2, 3])

# Repeat each element in the array 3 times
repeated_arr = np.repeat(arr_base, 3)

# Print the resulting array with repeated elements
print(repeated_arr)

[1 1 1 2 2 2 3 3 3]


In [45]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3]])

# Repeat the rows of the array 3 times along axis 0
repeated_rows_arr = np.repeat(arr_2d, 3, axis=0)

# Print the resulting array with repeated rows
print(repeated_rows_arr)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


### Array Rearrangement and Copying

In [46]:
# Create a NumPy array
arr_orig = np.array([1, 2, 3])

# Reference arr_ref to arr_orig (not a copy)
arr_ref = arr_orig

# Printing original and referenced arrays
print("Original array (arr_orig):", arr_orig)
print("Referenced array (arr_ref):", arr_ref, "\n")

# Modifying the first element of arr_ref, which also affects arr_orig
arr_ref[0] = 100

# Printing both arrays after modification
print("Modified original array (arr_orig):", arr_orig)
print("Modified referenced array (arr_ref):", arr_ref, "\n")

# To avoid this shared reference and create a true copy, we use the .copy() method
arr_copy = arr_orig.copy()
arr_copy[0] = 200

# Printing after creating a true copy
print("Original array (arr_orig) after copy:", arr_orig)
print("Copied array (arr_copy):", arr_copy)

Original array (arr_orig): [1 2 3]
Referenced array (arr_ref): [1 2 3] 

Modified original array (arr_orig): [100   2   3]
Modified referenced array (arr_ref): [100   2   3] 

Original array (arr_orig) after copy: [100   2   3]
Copied array (arr_copy): [200   2   3]


In [47]:
# Create a 2D NumPy array
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Resize the array to a new shape (4, 2)
# The resized array will be filled by repeating the original array if necessary
resized_arr = np.resize(arr2d, (4, 2))

# Print the resized array
print(resized_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [48]:
# Resize the array to a new shape (4, 4)
# The resized array will repeat the original array's values to fill the new shape
resized_arr2 = np.resize(arr2d, (4, 4))

# Print the resized array
print(resized_arr2)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [49]:
# Resize the array to shape (4, 3)
resized_arr3 = np.resize(arr2d, (4, 3))

# Print the resized array
print(resized_arr3)

[[1 2 3]
 [4 5 6]
 [7 8 1]
 [2 3 4]]


In [50]:
# Reshape the array to shape (4, 2)
# The reshape operation will rearrange the data without modifying it
# It's important to note that the new shape must have the same total number of elements as the original array

reshaped_arr = np.reshape(arr2d, (4, 2))

# Print the reshaped array
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [51]:
# Reshape the array to shape (8, 1)
# This is valid because the total number of elements (8) remains the same.
reshaped_arr1 = np.reshape(arr2d,(8,1))
print(reshaped_arr1)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [52]:
# Flatten the array into a 1D array
flattened_arr = arr2d.flatten()

# Print the flattened array
print(flattened_arr)

[1 2 3 4 5 6 7 8]


In [53]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([6, 7, 8, 9, 0])

# Vertically stacking v1 and v2
result = np.vstack([v1, v2])
print(result)

#For vertical stacking, the number of columns must be the same for all arrays being stacked

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [54]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([6, 7, 8, 9, 0])

# Horizontally stacking v1 and v2
result = np.hstack([v1, v2])
print(result)

#For horizontal stacking, the number of rows must be the same for all arrays being stacked

[1 2 3 4 5 6 7 8 9 0]


### Mathematics

In [55]:
# Creating 2D arrays A and B
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Array A:")
print(A)

print("\nArray B:")
print(B)

Array A:
[[1 2]
 [3 4]]

Array B:
[[5 6]
 [7 8]]


In [56]:
# Mechanism that is common for all operators
# Result[i] = Array[i] operator value

# Add 2 to each element of array A
add_result = A + 2
print("Addition of 2 to each element in A:")
print(add_result)

# Subtract 2 from each element of array A
sub_result = A - 2
print("\nSubtraction of 2 from each element in A:")
print(sub_result)

# Multiply each element of array A by 2
mul_result = A * 2
print("\nMultiplication of each element in A by 2:")
print(mul_result)

# Divide each element of array A by 2
div_result = A / 2
print("\nDivision of each element in A by 2:")
print(div_result)

# Floor division of each element of array A by 2
floor_div_result = A // 2
print("\nFloor division of each element in A by 2:")
print(floor_div_result)

# Modulo operation on each element of array A by 2
mod_result = A % 2
print("\nModulo operation (remainder when divided by 2) on each element in A:")
print(mod_result)

# Element-wise power operation (raising each element to the power of 2)
pow_result = A ** 2
print("\nRaising each element in A to the power of 2:")
print(pow_result)

Addition of 2 to each element in A:
[[3 4]
 [5 6]]

Subtraction of 2 from each element in A:
[[-1  0]
 [ 1  2]]

Multiplication of each element in A by 2:
[[2 4]
 [6 8]]

Division of each element in A by 2:
[[0.5 1. ]
 [1.5 2. ]]

Floor division of each element in A by 2:
[[0 1]
 [1 2]]

Modulo operation (remainder when divided by 2) on each element in A:
[[1 0]
 [1 0]]

Raising each element in A to the power of 2:
[[ 1  4]
 [ 9 16]]


In [57]:
# Mechanism that is common for all operators
# Result[i, j] = Array1[i, j] operator Array2[i, j]

# Add arrays A and B
add_result = A + B
print("Addition of A and B:")
print(add_result)

# Subtract array B from array A
sub_result = A - B
print("\nSubtraction of B from A:")
print(sub_result)

# Multiply arrays A and B
mul_result = A * B
print("\nMultiplication of A and B:")
print(mul_result)

# Divide array A by array B
div_result = A / B
print("\nDivision of A by B:")
print(div_result)

# Floor divide array A by array B
floor_div_result = A // B
print("\nFloor division of A by B:")
print(floor_div_result)

# Modulo operation (remainder when A is divided by B)
mod_result = A % B
print("\nModulo operation (remainder when A is divided by B):")
print(mod_result)

# Exponentiation (A raised to the power of B)
pow_result = A ** B
print("\nExponentiation: A raised to the power of B:")
print(pow_result)

Addition of A and B:
[[ 6  8]
 [10 12]]

Subtraction of B from A:
[[-4 -4]
 [-4 -4]]

Multiplication of A and B:
[[ 5 12]
 [21 32]]

Division of A by B:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

Floor division of A by B:
[[0 0]
 [0 0]]

Modulo operation (remainder when A is divided by B):
[[1 2]
 [3 4]]

Exponentiation: A raised to the power of B:
[[    1    64]
 [ 2187 65536]]


In [58]:
# Take the sine of each element in array a (Element-wise sine)

# Compute sine of each angle in degrees
angles_deg = np.array([0, 30, 45, 60, 90])
sin_res1 = np.sin(angles_deg)
print("Sine of each angle in degrees : ")
print(sin_res1)

# Compute sine of each angle in radians
angles_rad = np.radians(angles_deg)
sin_res2 = np.sin(angles_rad)
print("Sine of each angle in radians : ")
print(sin_res2)

Sine of each angle in degrees : 
[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
Sine of each angle in radians : 
[0.         0.5        0.70710678 0.8660254  1.        ]


### Linear Algebra

In [59]:
# Matrix multiplication (Dot product of mat1 and mat2)

# mat1 is a 2x3 matrix filled with ones
mat1 = np.ones([2, 3], dtype="int16")

# mat2 is a 3x2 matrix filled with the number 2
mat2 = np.full([3, 2], 2, dtype="int16")

# Perform matrix multiplication using np.matmul()
result = np.matmul(mat1, mat2)

# Print the result of matrix multiplication
print(result)

[[6 6]
 [6 6]]


In [60]:
# mat3 = np.ones([2,3], dtype="int16")
# mat4 = np.full([2,3], 2, dtype="int16")
# print(np.matmul(m1,m2))

# Not possible because for matrix multiplication, the number of columns in mat3 (3) 
# must equal the number of rows in mat4 (2). Therefore, the operation cannot be performed.

In [61]:
# Find the determinant
mat5 = np.identity(3, dtype="int16")
print(np.linalg.det(mat5))

1.0


In [62]:
# Create a 4x4 matrix with arbitrary values
mat6 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Get the diagonal elements of mat6
print(np.diagonal(mat6))

[ 1  6 11 16]


In [63]:
# Get the diagonal elements of mat6
print(np.linalg.diagonal(mat6))

[ 1  6 11 16]


In [64]:
# Find the trace of mat6
print(np.trace(mat6))

34


In [65]:
# Find the trace of mat6
print(np.linalg.trace(mat6))

34


In [66]:
#Find the rank of mat6
print(np.linalg.matrix_rank(mat6))

2


In [67]:
#Find the transpose of mat6
print(np.linalg.matrix_transpose(mat6))

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [68]:
#Find the transpose of mat6
mat6.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [69]:
#Find the transpose of mat6
np.transpose(mat6)

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [70]:
#Find the inverse of mat6
mat7 = np.array([[1, 2, 3], [4,5,6], [7,2,9]])

print(np.linalg.inv(mat7))

[[-0.91666667  0.33333333  0.08333333]
 [-0.16666667  0.33333333 -0.16666667]
 [ 0.75       -0.33333333  0.08333333]]


### Statistics

In [71]:
# Given 2D array
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [72]:
# Minimum value in the entire array
print("\nMinimum value in the array:")
print(stats.min())
# print(np.min(stats))


Minimum value in the array:
1


In [73]:
# Maximum value in the entire array
print("\nMaximum value in the array:")
print(stats.max())
print(np.max(stats))


Maximum value in the array:
6
6


In [74]:
# Maximum value along each row (axis=1)
print("\nMaximum value along each row:")
print(np.max(stats, axis=1))


Maximum value along each row:
[3 6]


In [75]:
# Maximum value along each row (axis=0)
print("\nMaximum value along each row:")
print(np.max(stats, axis=0))


Maximum value along each row:
[4 5 6]


In [76]:
# Sum of all elements in the array
print("\nSum of the elements in the array:")
print(stats.sum())


Sum of the elements in the array:
21


In [77]:
# Sum along each column (axis 0)
print("\nSum along each column:")
print(stats.sum(axis=0))


Sum along each column:
[5 7 9]


In [78]:
# Sum along each row (axis 1)
print("\nSum along each row:")
print(stats.sum(axis=1))


Sum along each row:
[ 6 15]


In [79]:
# Mean of the entire array
print("\nMean of the array:")
print(stats.mean())


Mean of the array:
3.5


In [80]:
# Median of the entire array
print("\nMedian of the array:")
print(np.median(stats))


Median of the array:
3.5


In [81]:
# Variance of the entire array
print("\nVariance of the array:")
print(stats.var())


Variance of the array:
2.9166666666666665


In [82]:

# Standard deviation of the array
print("\nStandard Deviation of the array:")
print(stats.std())


Standard Deviation of the array:
1.707825127659933


In [83]:
# Percentile (e.g., 50th percentile)
print("\n50th Percentile (Median):")
print(np.percentile(stats, 50))


50th Percentile (Median):
3.5


In [84]:
# 25th Percentile
print("\n25th Percentile:")
print(np.percentile(stats, 25))


25th Percentile:
2.25


In [85]:
# 0th Percentile (Minimum Value)
print("\n0th Percentile (Minimum Value):")
print(np.percentile(stats, 0))


0th Percentile (Minimum Value):
1.0


In [86]:
# 75th Percentile
print("\n75th Percentile:")
print(np.percentile(stats, 75))


75th Percentile:
4.75


In [87]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,0])

np.vstack([v1,v2])

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [88]:
# Horizontally stacking vectors
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

### Miscellaneous

#### Load Data from file

In [89]:
# Read the data from "data.txt" file and convert it into a NumPy array
# dtype="int16" ensures the data is treated as 16-bit integers
# delimiter="," specifies that the values are separated by commas in the file
data = np.genfromtxt("data.txt", delimiter=",", dtype="int16")

# Print the loaded data
print(data)

[[ 1  2  3  4  5]
 [ 6  7 25  9  0]
 [ 3  4  2  6 50]]


In [90]:
# Read the data from the "data.txt" file
# The file is expected to be a comma-separated values
# We are not explicitly setting the data type here, so NumPy will infer the type
data = np.genfromtxt("data.txt", delimiter=",")

# Convert the data to 16-bit integers (int16) using astype() and print it
print(data.astype("int16"))

[[ 1  2  3  4  5]
 [ 6  7 25  9  0]
 [ 3  4  2  6 50]]


### Boolean Masking and Advanced indexing

In [91]:
# Create a boolean mask where the condition is data >= 50
mask = (data > 20)  # The condition checks if each element in 'data' is greater than or equal to 50
print(mask)

# Use the mask to select elements from the original 'data' array that satisfy the condition
filtered_data = data[mask]  # Only the elements where the condition is True are selected
print(filtered_data)

[[False False False False False]
 [False False  True False False]
 [False False False False  True]]
[25. 50.]


In [92]:
# Create a boolean mask where the condition is data > 20 and data < 100
mask = (data > 20) & (data < 100)  # Checks if elements are greater than 20 AND less than 100
print(mask)

# Use the mask to filter elements from 'data' that satisfy both conditions
filtered_data = data[mask]  # Only the elements where both conditions are True are selected
print(filtered_data)

[[False False False False False]
 [False False  True False False]
 [False False False False  True]]
[25. 50.]


In [93]:
# Indexing with a list in numpy
data_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Select elements at index 1, 3, and 5 from the array 'data_arr'
selected_values = data_arr[[1, 3, 5]]  # Using a list of indices to fetch specific elements
print(selected_values)

[2 4 6]
